name: Docs

on:
  push:
    branches:
      - master

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:2.9
        with:
          args: -o docs/examples/notebook.rst docs/examples/usage.ipynb
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing the library
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python setup.py install
          pip install .[docs]
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.1
        with:
          branch: master
          dir_docs: docs
          sphinxopts: ''
